Remove hack when creating and deleting reports
powsybl/powsybl-ws-commons pull request #66
Opened 2024-09-06 09:40 UTC by ayolab

**Please check if the PR fulfills these requirements**

- [ ] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**Does this PR already have an issue describing the problem?**

**What kind of change does this PR introduce?**

**What is the current behavior?**

**What is the new behavior (if this is a feature change)?**

**Does this PR introduce a breaking change or deprecate an API?**
- [ ] Yes
- [ ] No

**If yes, please check if the following requirements are fulfilled**

- [ ] The *Breaking Change* or *Deprecated* label has been added
- [ ] The migration steps are described in the following section

**What changes might users need to make in their application due to this PR? (migration steps)**

**Other information**:

2024-09-06 14:29 UTC, TheMaskedTurtle approved these changes
I think we should wait for the release with springboot to not block it but then ok !

2024-09-06 14:36 UTC, TheMaskedTurtle requested changes

2024-09-06 14:36 UTC, TheMaskedTurtle commented on src/test/java/com/powsybl/ws/commons/computation/service/ReportServiceTest.java
URL assertions should be changed tests don't pass

2024-09-06 14:56 UTC, ayolab commented on src/test/java/com/powsybl/ws/commons/computation/service/ReportServiceTest.java
Done

2024-09-12 16:15 UTC, dbraquart reviewed
code: OK
tests:on going

Note: When I upgrade voltage-init-server to use this PR, I have 2 compilation errors ! I had to fix them to run the server.  And I also had a test failure (testStop).

2024-09-23 08:44 UTC, TheMaskedTurtle requested changes

2024-09-23 08:44 UTC, TheMaskedTurtle commented on src/main/java/com/powsybl/ws/commons/computation/service/AbstractWorkerService.java
> +                        }
This changes the behavior, are we sure this is what we want ?

2024-09-23 08:44 UTC, TheMaskedTurtle commented on src/main/java/com/powsybl/ws/commons/computation/service/AbstractWorkerService.java
> +                        }
Here we catch all errors even 5xx not only 404

2024-09-24 07:56 UTC, TheMaskedTurtle approved these changes

2024-09-24 12:22 UTC, merged